installCRDs: true

## Node affinity for particular node in which labels key is "Infra-Services" and value is "true"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "Addons-Services"
          operator: In
          values:
          - "true"

resources:
  limits:
    cpu: 50m
    memory: 300Mi
  requests:
    cpu: 10m
    memory: 150Mi

webhook:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "Addons-Services"
            operator: In
            values:
            - "true"
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 50Mi

  podAnnotations:
    co.elastic.logs/enabled: "true"

cainjector:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "Addons-Services"
            operator: In
            values:
            - "true"
  resources:
    limits:
      cpu: 100m
      memory: 250Mi
    requests:
      cpu: 10m
      memory: 200Mi

  podAnnotations:
    co.elastic.logs/enabled: "true"
# we have to install ServiceMonitor CRD first
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
    labels:
      release: "prometheus-operator"
