
## Node affinity for particular node in which labels key is "Infra-Services" and value is "true"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "Addons-Services"
          operator: In
          values:
          - "true"

resources:
  limits:
    cpu: 100m
    memory: 400Mi
  requests:
    cpu: 10m
    memory: 200Mi

webhook:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "Addons-Services"
            operator: In
            values:
            - "true"
  resources:
    limits:
      cpu: 150m
      memory: 150Mi
    requests:
      cpu: 10m
      memory: 75Mi

cainjector:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "Addons-Services"
            operator: In
            values:
            - "true"
  resources:
    limits:
      cpu: 150m
      memory: 300Mi
    requests:
      cpu: 10m
      memory: 240Mi
