controller:
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 1Gi

podAnnotations:
  co.elastic.logs/enabled: "true"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "Addons-Services"
          operator: In
          values:
          - "true"
